
# Price Synchronization Configuration

websocket:
  enabled: true
  url: "wss://stream.bybit.com/v5/public/linear"
  symbols: 
    - "BTCUSDT"
    - "ETHUSDT" 
    - "SOLUSDT"
    - "DOGEUSDT"
  reconnect_timeout: 5  # seconds
  heartbeat_interval: 30  # seconds

time_sync:
  enabled: true
  interval: 60  # seconds between synchronizations
  threshold: 0.5  # difference threshold for warnings (seconds)
  samples: 3  # number of samples to take for offset calculation

monitoring:
  enabled: true
  alert_threshold: 5.0  # USD price difference threshold for alerts
  latency_threshold: 500  # milliseconds
  report_interval: 3600  # seconds (1 hour)
  history_file: "price_monitor_history.csv"

fallback:
  enabled: true  # Enable REST API fallback
  max_retry: 3  # Maximum retry attempts
  timeout: 2  # seconds
